call code --install-extension christian-kohler.npm-intellisense
call code --install-extension daltonjorge.scala
call code --install-extension DavidAnson.vscode-markdownlint
call code --install-extension EditorConfig.EditorConfig
call code --install-extension eg2.tslint
call code --install-extension eg2.vscode-npm-script
call code --install-extension esbenp.prettier-vscode
call code --install-extension keyring.Lua
call code --install-extension ms-python.python
call code --install-extension ms-vscode.csharp
call code --install-extension msjsdiag.debugger-for-chrome
call code --install-extension PeterJausovec.vscode-docker
call code --install-extension richie5um2.vscode-sort-json
call code --install-extension shd101wyy.markdown-preview-enhanced
call code --install-extension Tyriar.sort-lines
call code --install-extension whizkydee.material-palenight-theme
